name: main-website
services:
  mv_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mw-app
#    command: tail -f /dev/null
    command: "npm start"
    environment:
      - VIRTUAL_HOST=nailtech.loc
      - VIRTUAL_PORT=3000
    volumes:
      - ../:/app
    networks:
      - mw-network
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
  mw-network:
    driver: bridge
